### ISSUE TITLE
FlyCheck reports error "user-error: Flycheck mode disabled"

### ISSUE THREAD

**Issue by geraldus** [chrisdone/haskell-flycheck#4]
I've put this script to my `load-path` and added to my init file `(require 'haskell-flycheck)`.
Then If I disabling `haskell-ghc` checker as Luke Hoersten suggests, FlyCheck reports error `user-error: Flycheck mode disabled`; usually FlyCheck continues to work, but sometimes it does not.

**Comment by geraldus** [comment]
For instance, this error occurs when I try to infer type `haskell-mode-show-type-at`, here is debugger output:

```el
Debugger entered--Lisp error: (user-error "Flycheck mode disabled")
  signal(user-error ("Flycheck mode disabled"))
  user-error("Flycheck mode disabled")
  flycheck-buffer()
  flycheck-disable-checker(haskell-ghc)
  (lambda nil (flycheck-disable-checker (quote haskell-ghc)))()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook haskell-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook haskell-mode-hook))
  run-mode-hooks(haskell-mode-hook)
  haskell-mode()
  haskell-fontify-as-mode("main :: IO ()" haskell-mode)
  haskell-mode-show-type-at(nil)
  call-interactively(haskell-mode-show-type-at nil nil)
  command-execute(haskell-mode-show-type-at)
```

**Comment by LukeHoersten** [comment]
The docker minimal test case you send me: https://github.com/geraldus/emacs-docker/blob/master/init.el

**Comment by geraldus** [comment]
Here is the image itself https://registry.hub.docker.com/u/geraldus/emacs-testbox/
I still need to tidy up things a bit, but it should work already. Will ping you later.

**Comment by geraldus** [comment]
I'm still unsure about it, but when I have looked at output once again and got some insight.

Look, I've ran `haskell-mode-show-type-at` and likely it was executed and gave correct result (I've reversed output everywhere to make it easy to read from top to bottom):
``` elisp
  command-execute(haskell-mode-show-type-at)
  call-interactively(haskell-mode-show-type-at nil nil)
  haskell-mode-show-type-at(nil)
  haskell-fontify-as-mode("main :: IO ()" haskell-mode)
```
After that, `haskell-mode-hook` is being called, including all its hooks:
```elips
  haskell-mode()
  run-mode-hooks(haskell-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook haskell-mode-hook))
  run-hooks(change-major-mode-after-body-hook prog-mode-hook haskell-mode-hook)
```
I have a hook which removes `haskell-ghc` checker from FlyCheck checkers list:
```elisp
  (lambda nil (flycheck-disable-checker (quote haskell-ghc)))()
  flycheck-disable-checker(haskell-ghc)
```
So far so good. But now `flycheck-buffer` is called:
```elips
  flycheck-buffer()
```
Which finally gives mentioned error:
``` elisp
  user-error("Flycheck mode disabled")
  signal(user-error ("Flycheck mode disabled"))
```
So it turns that possible crux of the matter is the way I'm disabling **haskell-ghc** checker, though I can't figure out what makes FlyCheck to report this user error: I'm able successfully run following commands using `M-x` or `eval-expression`:

+ `(lambda nil (flycheck-disable-checker (quote haskell-ghc)))`
+ `(flycheck-buffer)`
+ `flycheck-disable-checker` interactively via `M-x`

I'll try to have a look ay FlyCheck sources to figure out where does this user error comes from.

**Comment by geraldus** [comment]
Okay, I have following workaround for now:
```el
(add-hook 'after-init-hook (lambda () (delete 'haskell-ghc flycheck-checkers)))
```
This permanently removes `haskell-ghc` checker from FlyCheck checkers list, no user errors anymore!
